version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14.17.1
    working_directory: ~/repo/FitCzar-fitness-App/Frontend with backend integration
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Run Jest tests
          command: yarn test

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
