version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14.17.1
    steps:
      - checkout
      - run: cd Frontend with backend integration && yarn install
      - run:
          name: Run Jest tests
          command: cd Frontend with backend integration && yarn test

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build_and_test
